.TH LSB-RPM 1
.SH NAME
lsb-rpm \- LSB compatible RPM
.SH SYNOPSIS
.B lsb-rpm
.SH "DESCRIPTION"
This is a special version of rpm that is linked statically and can be
used in LSB build environment. For full documentation of parameters,
see rpm(8).
.SH "SEE ALSO"
.BR rpm(8)
,
.BR lsb-rpmbuild(8)
.SH AUTHOR
This manual page was written by Joey Hess,
for the Debian GNU/Linux system.
